### ISSUE TITLE
Notifycontroller sql improvements

### ISSUE THREAD

**Issue by lortizcompegps** [pagantis/magento-1X#53]
app/code/community/Pagantis/Pagantis/controllers/NotifyController.php
protected function blockConcurrency($orderId)

        $sql = "INSERT INTO  " . self::CONCURRENCY_TABLENAME . "  VALUE ('" . $orderId. "'," . time() . ")";

    protected function unblockConcurrency($orderId = null)
    {
        if ($orderId == null) {
            $sql = "DELETE FROM " . self::CONCURRENCY_TABLENAME . " WHERE timestamp <" . (time() - 10);
        } else {
            $sql = "DELETE FROM " . self::CONCURRENCY_TABLENAME . " WHERE id  = '" . $orderId . "'";
        }
        try 

is recommended to simple quote orderid, because, orderid sometimes could be alfanumeric

**Comment by pgarcess** [comment]
It will be included in the next release
