### ISSUE TITLE
PAGANTIS_PROMOTION_MESSAGE is deleted in upgrade 8.2.5

### ISSUE THREAD

**Issue by lortizcompegps** [pagantis/magento-1X#54]
upgrade sql script 8.1.0-8.2.0 create this field

$installer->run("INSERT INTO `pagantis_config` 
    (`config`, `value`)
    VALUES
    ('PAGANTIS_PROMOTION_MESSAGE', 'Finance this product <span class=\"pmt-no-interest\">without interest!</span>')");

but when you upgrade to 8.2.5 this field is deleted, because install script of 8.2.5 version drop this table when install

app/code/community/Pagantis/Pagantis/sql/pagantis_setup/install-8.2.5.php
$installer->run('DROP TABLE IF EXISTS `pagantis_config`');
$installer->run('CREATE TABLE `pagantis_config` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `config` VARCHAR(60) NOT NULL,
  `value` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`id`)
  )');

$installer->run("INSERT INTO `pagantis_config` 
    (`config`, `value`)
    VALUES
    ('PAGANTIS_TITLE', 'Instant Financing'),
    ('PAGANTIS_SIMULATOR_DISPLAY_TYPE', 'pgSDK.simulator.types.SIMPLE'),
    ('PAGANTIS_SIMULATOR_DISPLAY_SKIN', 'pgSDK.simulator.skins.BLUE'),
    ('PAGANTIS_SIMULATOR_DISPLAY_POSITION', 'hookDisplayProductButtons'),
    ('PAGANTIS_SIMULATOR_START_INSTALLMENTS', '3'),
    ('PAGANTIS_SIMULATOR_CSS_POSITION_SELECTOR', 'default'),
    ('PAGANTIS_SIMULATOR_DISPLAY_CSS_POSITION', 'pgSDK.simulator.positions.INNER'),
    ('PAGANTIS_SIMULATOR_CSS_PRICE_SELECTOR', 'default'),
    ('PAGANTIS_SIMULATOR_CSS_QUANTITY_SELECTOR', 'default'),
    ('PAGANTIS_FORM_DISPLAY_TYPE', '0'),
    ('PAGANTIS_DISPLAY_MIN_AMOUNT', '1'),
    ('PAGANTIS_URL_OK', 'checkout/onepage/success/'),
    ('PAGANTIS_ALLOWED_COUNTRIES', 'a:3:{i:0;s:2:\"es\";i:1;s:2:\"it\";i:2;s:2:\"fr\";}'),
    ('PAGANTIS_URL_KO', 'checkout/cart/'),
    ('PAGANTIS_SIMULATOR_THOUSANDS_SEPARATOR', '.'),
    ('PAGANTIS_SIMULATOR_DECIMAL_SEPARATOR', ',')");

So, PAGANTIS_PROMOTION_MESSAGE doesn't exist anymore.

**Comment by pgarcess** [comment]
Sorry this issue is out of date, I have seen too late.

If you need more information or something else, do not hesitate to contact with us.
