### ISSUE TITLE
PHP Fatal error:  require_once(): Failed opening required '.../lib/DigitalOrigin/autoload.php'

### ISSUE THREAD

**Issue by raulsinapsis** [pagantis/magento-1X#7]
Hi there,
It seems some files are missing in your package
This is called at DigitalOrigin_Pmt_Model_Observer::addAutoloader()

**Comment by romeritoCL** [comment]
Hi, 

I have added a new version with fixed autoloader. I have double checked the warnings on the system.log and seems to have been fixed.

**Comment by romeritoCL** [comment]
From tag 6.2.2 this issue is fixed. Thanks for the notification and for the help.

**Comment by raulsinapsis** [comment]
mmm I don't see any lib/DigitalOrigin folder in the zip yet
